/* ═══════════════════════════════════════════
   Capstone Project Flashcards
   Auto-generated — Do not edit manually
   ═══════════════════════════════════════════ */

const FLASHCARD_DATA = [

  // ── Agile & Scrum ──

  { id: 1, category: "Agile & Scrum", q: "In Agile development, what is a 'Sprint'?", a: "A development iteration, usually lasting 2 to 4 weeks." },
  { id: 2, category: "Agile & Scrum", q: "Define 'Velocity' in the context of Scrum project management.", a: "An estimate of how much product backlog effort a team can cover in a single sprint." },
  { id: 3, category: "Agile & Scrum", q: "What is the primary responsibility of the 'ScrumMaster'?", a: "Interfacing with the rest of the company and protecting the team from outside interference." },
  { id: 4, category: "Agile & Scrum", q: "In Scrum, development iterations are usually _____ long.", a: "2-4 weeks" },
  { id: 5, category: "Agile & Scrum", q: "Scrum developers are adamant that the ScrumMaster is not a _____.", a: "project manager" },
  { id: 6, category: "Agile & Scrum", q: "Why do Scrum developers insist that the ScrumMaster is not a project manager?", a: "Because the ScrumMaster focuses on interfacing with the company and protecting the team from outside interference." },
  { id: 7, category: "Agile & Scrum", q: "What is a 'Sprint' in the context of Scrum development?", a: "A development iteration, usually 2-4 weeks long." },
  { id: 8, category: "Agile & Scrum", q: "Term: Velocity (Scrum)", a: "Definition: An estimate of how much product backlog effort a team can cover in a single sprint." },
  { id: 9, category: "Agile & Scrum", q: "Why might developers take 'short cuts' when writing tests in an agile environment?", a: "To save time, often resulting in incomplete tests that ignore possible exceptions." },
  { id: 10, category: "Agile & Scrum", q: "Contrast the role of a ScrumMaster with that of a traditional project manager.", a: "A ScrumMaster interfaces with the company and protects the team from interference rather than managing tasks." },
  { id: 11, category: "Agile & Scrum", q: "In Scrum, what is a 'Sprint'?", a: "A development iteration typically lasting 2 to 4 weeks." },
  { id: 12, category: "Agile & Scrum", q: "Define 'Velocity' in the context of Scrum team performance.", a: "An estimate of the amount of product backlog effort a team can complete in a single sprint." },
  { id: 13, category: "Agile & Scrum", q: "How could Model-Driven Architecture (MDA) theoretically support agile development?", a: "By completely automating transformations from a PIM to a program, eliminating separate coding." },
  { id: 14, category: "Agile & Scrum", q: "What is the 'fundamental contradiction' between MDA and the Agile Manifesto?", a: "Agile prioritizes code/individuals over extensive up-front modeling required by MDA." },
  { id: 15, category: "Agile & Scrum", q: "In Scrum, the team's capacity for work is measured by its _____.", a: "Velocity" },
  { id: 16, category: "Agile & Scrum", q: "In Extreme Programming (XP), how are user requirements typically expressed?", a: "As user stories or scenarios." },
  { id: 17, category: "Agile & Scrum", q: "What physical medium is traditionally used to record user stories in XP development?", a: "Cards." },
  { id: 18, category: "Agile & Scrum", q: "What is the relationship between user stories and implementation tasks in an XP team?", a: "The development team breaks stories down into smaller implementation tasks." },
  { id: 19, category: "Agile & Scrum", q: "What is the 'conventional wisdom' regarding change in software engineering that refactoring challenges?", a: "Conventional wisdom suggests designing for change by anticipating it early to reduce later costs." },
  { id: 20, category: "Agile & Scrum", q: "Why might XP testers write incomplete tests that fail to check for all possible exceptions?", a: "They sometimes take short cuts when writing tests under pressure." },
  { id: 21, category: "Agile & Scrum", q: "What is the primary responsibility of a ScrumMaster regarding the Scrum team's environment?", a: "Ensuring the team is not diverted by outside interference." },
  { id: 22, category: "Agile & Scrum", q: "How do Scrum developers distinguish the ScrumMaster role from a traditional project manager?", a: "They are adamant that the ScrumMaster is not a project manager." },
  { id: 23, category: "Agile & Scrum", q: "What is the typical duration of a Sprint in the Scrum methodology?", a: "Between $2$ and $4$ weeks." },
  { id: 24, category: "Agile & Scrum", q: "Define 'Velocity' in the context of a Scrum development team.", a: "An estimate of how much product backlog effort a team can cover in a single sprint." },
  { id: 25, category: "Agile & Scrum", q: "How does 'Velocity' assist a Scrum team in project planning?", a: "It helps the team estimate how many items from the backlog they can realistically complete in future sprints." },
  { id: 26, category: "Agile & Scrum", q: "In the context of refactoring, what is the primary benefit of spending time to anticipate change?", a: "It reduces the long-term costs of the software life cycle." }
  // ── Behavioral & State Modeling ──

,
  { id: 27, category: "Behavioral & State Modeling", q: "State machine models show the system's _____ and the events that cause transitions.", a: "states" },
  { id: 28, category: "Behavioral & State Modeling", q: "The state where a microwave is waiting for the user to press 'Start' is the _____ state.", a: "Enabled" },
  { id: 29, category: "Behavioral & State Modeling", q: "What do state diagrams model in response to internal or external events?", a: "A system's dynamic behavior." },
  { id: 30, category: "Behavioral & State Modeling", q: "What is the main limitation of 'Activity diagrams' in system modeling?", a: "They model process steps but may not capture the fine-grained logic of data transformations." }
  // ── Design Patterns ──

,
  { id: 31, category: "Design Patterns", q: "In the Observer design pattern, what is the role of the 'ConcreteSubject'?", a: "It notifies observers when its state has changed and allows adding or removing observers." },
  { id: 32, category: "Design Patterns", q: "In the Observer design pattern, what is the role of the 'ConcreteObserver'?", a: "It maintains a copy of the subject's state and implements an update interface to stay in step." },
  { id: 33, category: "Design Patterns", q: "Design patterns describe commonly occurring _____ in software design.", a: "problems and their solutions" },
  { id: 34, category: "Design Patterns", q: "In the Observer pattern, which component issues a notification when its state has changed?", a: "The ConcreteSubject" },
  { id: 35, category: "Design Patterns", q: "What is the role of the 'Update()' interface in the Observer pattern?", a: "It allows ConcreteObservers to keep their copies of the subject's state in step." },
  { id: 36, category: "Design Patterns", q: "In the Observer pattern, what is the role of the 'ConcreteSubject'?", a: "It maintains the state of interest and sends a notification to observers when that state changes." },
  { id: 37, category: "Design Patterns", q: "How does a 'ConcreteObserver' maintain consistency with the 'ConcreteSubject'?", a: "It implements an Update() interface to keep its copy of the state in step with the subject." },
  { id: 38, category: "Design Patterns", q: "What is the primary architectural consequence of the Observer pattern?", a: "The subject only knows the abstract Observer interface, decoupling it from specific observer details." },
  { id: 39, category: "Design Patterns", q: "The _____ pattern allows multiple displays to reflect the same underlying data changes automatically.", a: "Observer" },
  { id: 40, category: "Design Patterns", q: "In the Observer pattern, the _____ issues a notification when its state has changed.", a: "ConcreteSubject" },
  { id: 41, category: "Design Patterns", q: "Define a 'design pattern' in software engineering.", a: "A way of reusing abstract knowledge about a problem and its solution." },
  { id: 42, category: "Design Patterns", q: "Which element of a pattern description serves as its meaningful identifier?", a: "The Name." },
  { id: 43, category: "Design Patterns", q: "In the Observer pattern, what is the role of the 'ConcreteObserver'?", a: "It maintains a copy of the subject's state and updates it to reflect changes." },
  { id: 44, category: "Design Patterns", q: "Which design pattern is used to provide a standard way of accessing elements in a collection independently of its implementation?", a: "The Iterator pattern." },
  { id: 45, category: "Design Patterns", q: "What is the goal of the 'Facade' pattern?", a: "To tidy up the interfaces of a number of related objects developed incrementally." },
  { id: 46, category: "Design Patterns", q: "In the Observer pattern, why does the 'Subject' only know the 'Observer' as an abstract interface?", a: "To decouple the subject from the specific details of its concrete observers." }
  // ── Model-Driven Engineering ──

,
  { id: 47, category: "Model-Driven Engineering", q: "Why are companies reluctant to adopt MDA for long-lifetime systems?", a: "They fear specialized tool vendors going out of business or the high cost of developing custom tools." },
  { id: 48, category: "Model-Driven Engineering", q: "Why might the abstractions in MDA models be insufficient for system implementation?", a: "Abstractions useful for design discussions may not capture implementation details like security or legacy integration." },
  { id: 49, category: "Model-Driven Engineering", q: "Model-Driven Architecture often lacks specialized _____ support, limiting its adoption.", a: "Tool" },
  { id: 50, category: "Model-Driven Engineering", q: "What is the core idea behind 'Model-driven engineering'?", a: "A system is represented as models that are automatically transformed into executable code." }
  // ── Reliability & Availability ──

,
  { id: 51, category: "Reliability & Availability", q: "Non-functional requirements that specify behavioral characteristics like execution speed or reliability are called _____ requirements.", a: "product" },
  { id: 52, category: "Reliability & Availability", q: "Define 'Availability' in reliability engineering.", a: "A measure of the fraction of time that a system is available for use, taking repair and restart time into account." },
  { id: 53, category: "Reliability & Availability", q: "What does an availability of 0.999 mean in terms of daily downtime?", a: "The system is unavailable for 84 seconds in a 24-hour period." },
  { id: 54, category: "Reliability & Availability", q: "What does an availability of 0.99 mean in terms of daily downtime?", a: "The system is unavailable for 14.4 minutes in a 24-hour period." },
  { id: 55, category: "Reliability & Availability", q: "How can high-availability be achieved in critical systems like the Airbus flight control system?", a: "By using several self-checking systems in parallel." },
  { id: 56, category: "Reliability & Availability", q: "Why must software in redundant channels be diverse?", a: "To ensure the same software error does not affect every channel simultaneously." },
  { id: 57, category: "Reliability & Availability", q: "What architectural feature does the Airbus FCS use to prevent common mode hardware failures?", a: "Diversity, such as using different processors and chipsets for primary and secondary systems." },
  { id: 58, category: "Reliability & Availability", q: "Why should you include timeouts when calling external components in a distributed system?", a: "To avoid waiting indefinitely for a response if the remote computer fails silently." },
  { id: 59, category: "Reliability & Availability", q: "In static analysis, what is an example of a 'Control fault'?", a: "Unreachable code or unconditional branches into loops." },
  { id: 60, category: "Reliability & Availability", q: "In static analysis, what is an example of a 'Storage management fault'?", a: "Unassigned pointers or pointer arithmetic." },
  { id: 61, category: "Reliability & Availability", q: "In static analysis, what is an example of an 'Interface fault'?", a: "Parameter-type mismatches or non-usage of function results." },
  { id: 62, category: "Reliability & Availability", q: "What does 'Dependability' include besides security?", a: "Reliability and safety." },
  { id: 63, category: "Reliability & Availability", q: "Availability takes _____ and restart time into account.", a: "repair" },
  { id: 64, category: "Reliability & Availability", q: "Availability of 0.998 means the software is available for _____ out of 1000 time units.", a: "998" },
  { id: 65, category: "Reliability & Availability", q: "Static analysis: A variable declared but never used is an example of a _____ fault.", a: "data" },
  { id: 66, category: "Reliability & Availability", q: "Static analysis: Variables output twice with no intervening assignment is an example of an _____ fault.", a: "input/output" },
  { id: 67, category: "Reliability & Availability", q: "In the Airbus FCS, how many separate computers can run the control software?", a: "5" },
  { id: 68, category: "Reliability & Availability", q: "Static analysis: 'Uncalled functions and procedures' are examples of _____ faults.", a: "interface" },
  { id: 69, category: "Reliability & Availability", q: "Static analysis: 'Variables assigned twice but never used' is a _____ fault.", a: "data" },
  { id: 70, category: "Reliability & Availability", q: "The Airbus FCS approach of using several systems in parallel is called a _____ system.", a: "self-monitoring" },
  { id: 71, category: "Reliability & Availability", q: "An availability of 0.9999 results in roughly _____ minute of downtime per week.", a: "one" },
  { id: 72, category: "Reliability & Availability", q: "Static analysis: 'Unassigned pointers' are classified as _____ faults.", a: "storage management" },
  { id: 73, category: "Reliability & Availability", q: "Static analysis: 'Parameter-type mismatches' are classified as _____ faults.", a: "interface" },
  { id: 74, category: "Reliability & Availability", q: "Static analysis: 'Unreachable code' is classified as a _____ fault.", a: "control" },
  { id: 75, category: "Reliability & Availability", q: "Availability is relevant for non-stop, _____ running systems.", a: "continuously" },
  { id: 76, category: "Reliability & Availability", q: "Static analysis: 'Undeclared variables' are classified as _____ faults.", a: "data" },
  { id: 77, category: "Reliability & Availability", q: "Static analysis: 'Pointer arithmetic' is classified as a _____ fault.", a: "storage management" },
  { id: 78, category: "Reliability & Availability", q: "Static analysis: 'Parameter number mismatches' are classified as _____ faults.", a: "interface" },
  { id: 79, category: "Reliability & Availability", q: "Which process quality attribute requires the model to be able to recover from failures of individual activities?", a: "Robust" },
  { id: 80, category: "Reliability & Availability", q: "A software process that includes redundant verification and validation activities is described as _____.", a: "Diverse" },
  { id: 81, category: "Reliability & Availability", q: "Term: Availability", a: "Definition: A measure of the fraction of time that a system is available for use, taking repair and restart time into account." },
  { id: 82, category: "Reliability & Availability", q: "If a system has an availability of $0.998$, how many time units out of 1000 is it available?", a: "$998$" },
  { id: 83, category: "Reliability & Availability", q: "An availability specification of $0.9$ means the system is unavailable for _____ minutes in a 24-hour period.", a: "$144$" },
  { id: 84, category: "Reliability & Availability", q: "What is the daily unavailable time for a system with $0.999$ availability?", a: "$84$ seconds" },
  { id: 85, category: "Reliability & Availability", q: "Which availability level corresponds roughly to 'one minute per week' of downtime?", a: "$0.9999$" },
  { id: 86, category: "Reliability & Availability", q: "What architectural approach does the Airbus flight control system use to achieve high availability?", a: "Parallel self-checking systems with diverse hardware and software." },
  { id: 87, category: "Reliability & Availability", q: "Why is diversity in software important in redundant multi-channel systems?", a: "To prevent the same software error from affecting all channels simultaneously." },
  { id: 88, category: "Reliability & Availability", q: "How many separate computers are utilized in the Airbus Flight Control System?", a: "$5$" },
  { id: 89, category: "Reliability & Availability", q: "Why should timeouts be included when calling external components in distributed systems?", a: "To avoid 'silent' failures where the system waits indefinitely for a response that never comes." },
  { id: 90, category: "Reliability & Availability", q: "What action should a system take after a defined timeout period has elapsed without a response from an external component?", a: "Assume failure and execute recovery actions." },
  { id: 91, category: "Reliability & Availability", q: "What is a characteristic error checked by static analyzers?", a: "Patterns in the code characteristic of errors made by programmers using a specific language." },
  { id: 92, category: "Reliability & Availability", q: "Name a common 'Storage management fault' detectable by static analysis.", a: "Memory leaks (or unassigned pointers)" },
  { id: 93, category: "Reliability & Availability", q: "What type of static analysis fault involves 'Unreachable code'?", a: "Control faults" },
  { id: 94, category: "Reliability & Availability", q: "What fault occurs when a variable is output twice with no intervening assignment?", a: "Input/output fault" },
  { id: 95, category: "Reliability & Availability", q: "Term: Interface fault", a: "Definition: Errors such as parameter-type mismatches or parameter number mismatches between components." },
  { id: 96, category: "Reliability & Availability", q: "What constitutes an 'Interface fault' in static analysis?", a: "Mismatches in parameter types or numbers, or non-usage of function results." },
  { id: 97, category: "Reliability & Availability", q: "List three examples of 'Storage management faults' identified by static analysis.", a: "Unassigned pointers, pointer arithmetic, and memory leaks." },
  { id: 98, category: "Reliability & Availability", q: "Identify two types of 'Data faults' discovered through static analysis of program code.", a: "Variables declared but never used or assigned twice without intervening use." },
  { id: 99, category: "Reliability & Availability", q: "Distinguish between 'System Fault' and 'System Error' in the reliability chain.", a: "A fault is a static characteristic (buggy code), while an error is an erroneous internal state during execution." },
  { id: 100, category: "Reliability & Availability", q: "Define 'System Failure' in reliability engineering.", a: "An event where the system does not deliver a service as expected by its users." },
  { id: 101, category: "Reliability & Availability", q: "Explain the relationship between human behavior and system faults.", a: "Human error or mistakes result in the introduction of faults into a software system." },
  { id: 102, category: "Reliability & Availability", q: "Why do system faults not always result in system errors?", a: "The faulty code might never be executed, or the state might be corrected before the error manifests." },
  { id: 103, category: "Reliability & Availability", q: "How can a system avoid failure even if a system error has occurred?", a: "Through built-in error detection and recovery mechanisms that correct the state." },
  { id: 104, category: "Reliability & Availability", q: "Define 'Availability' as a reliability metric.", a: "A measure of the fraction of time a system is available for use, accounting for repair and restart time." },
  { id: 105, category: "Reliability & Availability", q: "What does an availability of $0.998$ mean in practical terms?", a: "The system is available for 998 out of every 1000 time units." },
  { id: 106, category: "Reliability & Availability", q: "For which types of systems is availability most relevant?", a: "Non-stop, continuously running systems like telephone switching or railway signaling." },
  { id: 107, category: "Reliability & Availability", q: "How much downtime per 24-hour period is allowed by $0.99$ availability?", a: "14.4 minutes." },
  { id: 108, category: "Reliability & Availability", q: "What is the maximum daily downtime for a system with $0.9999$ availability?", a: "8.4 seconds (roughly one minute per week)." },
  { id: 109, category: "Reliability & Availability", q: "How can high availability be achieved using parallel systems?", a: "By using several self-checking systems in parallel, as seen in the Airbus flight control systems." },
  { id: 110, category: "Reliability & Availability", q: "What is 'diversity' in the context of the Airbus Flight Control System (FCS)?", a: "Using different processors, chipsets, and software versions to avoid common-mode failures." },
  { id: 111, category: "Reliability & Availability", q: "Describe the hardware architecture of the Airbus Flight Control System.", a: "It utilizes 5 separate computers, any of which can run the control software." },
  { id: 112, category: "Reliability & Availability", q: "In the Airbus FCS, how do the primary and secondary systems differ to ensure reliability?", a: "They use different processors and chipsets from different manufacturers." },
  { id: 113, category: "Reliability & Availability", q: "Why is the 'unconditional branch' (goto) considered an error-prone construct?", a: "It makes the program structure complex and difficult to follow, leading to faults." },
  { id: 114, category: "Reliability & Availability", q: "Why is 'Dynamic memory allocation' generally avoided in high-reliability systems?", a: "Run-time allocation can lead to memory overflow and unpredictable system behavior." },
  { id: 115, category: "Reliability & Availability", q: "How can 'Parallelism' lead to subtle timing errors?", a: "Unforeseen interactions between parallel processes can create race conditions or synchronization issues." },
  { id: 116, category: "Reliability & Availability", q: "Why are 'Interrupts' problematic for system understanding and reliability?", a: "They can terminate critical operations unexpectedly and make the program flow difficult to trace." },
  { id: 117, category: "Reliability & Availability", q: "Explain the reliability disadvantage of 'Inheritance' in object-oriented programming.", a: "Code is not localized, leading to unexpected behavior when changes are made to base classes." },
  { id: 118, category: "Reliability & Availability", q: "What specific failure is associated with 'Unbounded arrays'?", a: "Buffer overflow failures." },
  { id: 119, category: "Reliability & Availability", q: "Why should timeouts be used when calling external components in distributed systems?", a: "To prevent 'silent failures' where a program waits indefinitely for a response from a failed remote computer." },
  { id: 120, category: "Reliability & Availability", q: "Name a 'Data fault' where a variable is assigned twice but never used in between.", a: "Redundant assignment (or 'assigned twice but never used')." },
  { id: 121, category: "Reliability & Availability", q: "Define 'Unreachable code' as a static analysis fault.", a: "Code that can never be executed during program run-time, classified as a control fault." },
  { id: 122, category: "Reliability & Availability", q: "Why are 'Medical systems' and 'Aerospace systems' cited as needing special reliability techniques?", a: "They are critical systems where failure can result in significant loss of life or property." },
  { id: 123, category: "Reliability & Availability", q: "A characteristic of software that can lead to a system error is a _____.", a: "System Fault" },
  { id: 124, category: "Reliability & Availability", q: "The Airbus FCS uses _____ to ensure that a single software error doesn't affect all channels.", a: "Diversity (or Diverse Software)" },
  { id: 125, category: "Reliability & Availability", q: "Static analysis 'Interface faults' include parameter-type _____.", a: "Mismatches" },
  { id: 126, category: "Reliability & Availability", q: "A _____ fault is when a programmer loses track of relationships between system parts.", a: "Program (or Human Error leading to Fault)" },
  { id: 127, category: "Reliability & Availability", q: "Floating-point numbers are error-prone because they are inherently _____.", a: "Imprecise" },
  { id: 128, category: "Reliability & Availability", q: "Dormant faults are those that are _____ for many years.", a: "Undetected" },
  { id: 129, category: "Reliability & Availability", q: "Why can't users usually find errors in a formal specification to validate real requirements?", a: "Users rarely understand formal notations." },
  { id: 130, category: "Reliability & Availability", q: "What characteristic of formal program proofs makes them prone to containing errors, similar to large programs?", a: "Their large size and complexity." },
  { id: 131, category: "Reliability & Availability", q: "In static analysis, what category of fault includes 'unreachable code' and 'unconditional branches into loops'?", a: "Control faults." },
  { id: 132, category: "Reliability & Availability", q: "What specific static analysis fault is identified when a variable is output twice with no intervening assignment?", a: "Input/output faults." },
  { id: 133, category: "Reliability & Availability", q: "Static analysis identifies 'parameter-type mismatches' under which fault category?", a: "Interface faults." },
  { id: 134, category: "Reliability & Availability", q: "In storage management, what fault is characterized by a failure to deallocate memory, eventually exhausting resources?", a: "Memory leaks." },
  { id: 135, category: "Reliability & Availability", q: "In reliability engineering, what does 'Availability' measure?", a: "The fraction of time that a system is available for use." },
  { id: 136, category: "Reliability & Availability", q: "An availability of $0.998$ indicates the software is available for how many units out of $1000$?", a: "$998$ units." },
  { id: 137, category: "Reliability & Availability", q: "For an availability of $0.99$, what is the total maximum downtime allowed in a $24$-hour period?", a: "$14.4$ minutes." },
  { id: 138, category: "Reliability & Availability", q: "How much downtime does an availability of $0.9999$ allow per week, roughly?", a: "One minute per week." },
  { id: 139, category: "Reliability & Availability", q: "What approach is used by the Airbus flight control system to achieve high availability?", a: "Using several self-checking systems in parallel." },
  { id: 140, category: "Reliability & Availability", q: "In the Airbus FCS, how is hardware diversity achieved between primary and secondary systems?", a: "They use different processors and chipsets from different manufacturers." },
  { id: 141, category: "Reliability & Availability", q: "In a distributed system, why should you always include timeouts when calling external components?", a: "To avoid 'silent' failures where a program waits indefinitely for a response that will never arrive." }
  // ── Requirements Engineering ──

,
  { id: 142, category: "Requirements Engineering", q: "What is the primary focus of 'Software Specification'?", a: "Defining what the system should do." },
  { id: 143, category: "Requirements Engineering", q: "Software _____ involves changing the system in response to changing customer and market requirements.", a: "evolution" },
  { id: 144, category: "Requirements Engineering", q: "Define 'Requirements Engineering'.", a: "The process of establishing the services a customer requires from a system and the constraints under which it operates." },
  { id: 145, category: "Requirements Engineering", q: "What is the difference between 'Functional' and 'Non-functional' requirements?", a: "Functional requirements define system services, while non-functional requirements define constraints on those services." },
  { id: 146, category: "Requirements Engineering", q: "Non-functional requirements resulting from policies and procedures are classified as _____ requirements.", a: "organisational" },
  { id: 147, category: "Requirements Engineering", q: "What are 'External Requirements' in software engineering?", a: "Requirements that arise from factors external to the system and its development process." },
  { id: 148, category: "Requirements Engineering", q: "Why might non-functional requirements affect the overall architecture of a system?", a: "They often apply to the system as a whole rather than to individual components." },
  { id: 149, category: "Requirements Engineering", q: "Why is rapid software development often the most important requirement for modern businesses?", a: "Businesses operate in fast-changing environments where software must evolve quickly to reflect changing needs." },
  { id: 150, category: "Requirements Engineering", q: "What is the purpose of 'Requirements Validation'?", a: "To ensure the requirements actually define the system the customer wants." },
  { id: 151, category: "Requirements Engineering", q: "In the context of NFRs, what is a 'Security Requirement' an example of?", a: "A requirement that may generate several related functional requirements." },
  { id: 152, category: "Requirements Engineering", q: "What is 'Requirements Elicitation'?", a: "The process of gathering requirements from stakeholders." },
  { id: 153, category: "Requirements Engineering", q: "A set of software process activities includes: Specification, Design and implementation, Validation, and _____.", a: "Evolution" },
  { id: 154, category: "Requirements Engineering", q: "Functional requirements describe system _____.", a: "services" },
  { id: 155, category: "Requirements Engineering", q: "Non-functional requirements describe system _____.", a: "constraints" },
  { id: 156, category: "Requirements Engineering", q: "An example of an organizational requirement is _____ standards used.", a: "process" },
  { id: 157, category: "Requirements Engineering", q: "A requirement that the software must be compatible with other systems is an example of _____.", a: "Acceptability" },
  { id: 158, category: "Requirements Engineering", q: "What is 'Requirements Change'?", a: "The process of managing evolving requirements during the system lifecycle." },
  { id: 159, category: "Requirements Engineering", q: "The process of transforming a requirements specification into an executable system is _____.", a: "Design and implementation" },
  { id: 160, category: "Requirements Engineering", q: "In requirements engineering, 'constraints' define the _____ under which a system operates.", a: "limits or conditions" },
  { id: 161, category: "Requirements Engineering", q: "A security requirement may generate functional requirements that _____ existing requirements.", a: "restrict" },
  { id: 162, category: "Requirements Engineering", q: "An example of an external requirement is a _____ requirement.", a: "legislative or regulatory" },
  { id: 163, category: "Requirements Engineering", q: "The software engineering activity of changing software in response to new requirements is called software _____.", a: "Evolution" },
  { id: 164, category: "Requirements Engineering", q: "Who owns the specification and makes change decisions for generic software products?", a: "The software developer" },
  { id: 165, category: "Requirements Engineering", q: "In customized software products, who owns the specification and decides on required changes?", a: "The customer" },
  { id: 166, category: "Requirements Engineering", q: "Which software process model is characterized by separate and distinct phases of specification and development?", a: "The waterfall model" },
  { id: 167, category: "Requirements Engineering", q: "What process model interleaves the activities of specification, development, and validation?", a: "Incremental development" },
  { id: 168, category: "Requirements Engineering", q: "Why is the waterfall model only appropriate when requirements are well-understood?", a: "Because the inflexible partitioning makes responding to changing requirements difficult." },
  { id: 169, category: "Requirements Engineering", q: "How does incremental development affect the cost of accommodating changing requirements?", a: "The cost is reduced because less analysis and documentation needs to be redone." },
  { id: 170, category: "Requirements Engineering", q: "In the requirements engineering process, what is the purpose of elicitation and analysis?", a: "To determine what system stakeholders require or expect from the system." },
  { id: 171, category: "Requirements Engineering", q: "Term: Requirements specification", a: "Definition: The process of defining the requirements in detail." },
  { id: 172, category: "Requirements Engineering", q: "What is the purpose of requirements validation?", a: "To check the validity of the requirements." },
  { id: 173, category: "Requirements Engineering", q: "What section of a requirements document defines technical terms to avoid reader assumptions?", a: "Glossary" },
  { id: 174, category: "Requirements Engineering", q: "Which section of a requirements document describes how a system fits into the business objectives of an organization?", a: "Introduction" },
  { id: 175, category: "Requirements Engineering", q: "List the four generic activities common to all Requirements Engineering (RE) processes.", a: "Elicitation, analysis, validation, and management." },
  { id: 176, category: "Requirements Engineering", q: "How are the generic activities of Requirements Engineering (RE) executed in practice?", a: "They are interleaved iteratively rather than performed in a strict linear sequence." },
  { id: 177, category: "Requirements Engineering", q: "Describe the spiral view of the Requirements Engineering process.", a: "An iterative approach moving from business requirements to user requirements and finally system requirements." },
  { id: 178, category: "Requirements Engineering", q: "What is the purpose of 'Requirements Validation' in the RE spiral?", a: "To check that the requirements actually define the system that the customer wants." },
  { id: 179, category: "Requirements Engineering", q: "What does 'Requirements Discovery' (or discovery stage) involve?", a: "Interacting with stakeholders to gather information about required and existing systems." },
  { id: 180, category: "Requirements Engineering", q: "How does 'Requirements Classification and Organization' aid the RE process?", a: "It groups related requirements into coherent clusters for better management." },
  { id: 181, category: "Requirements Engineering", q: "Who are considered 'stakeholders' in the requirements discovery process?", a: "Anyone from managers and end-users to external regulators." },
  { id: 182, category: "Requirements Engineering", q: "What is the function of the 'Glossary' in a standard software requirements document?", a: "To define technical terms so that no assumptions are made about the reader's expertise." },
  { id: 183, category: "Requirements Engineering", q: "What should the 'Introduction' of a requirements document describe?", a: "The need for the system, its functions, and how it fits business strategic objectives." },
  { id: 184, category: "Requirements Engineering", q: "The process of gathering information to distill user and system requirements is _____.", a: "Requirements Discovery" },
  { id: 185, category: "Requirements Engineering", q: "Requirements engineering is considered an _____ activity because processes are interleaved.", a: "Iterative" },
  { id: 186, category: "Requirements Engineering", q: "Requirements discovery involves interaction with system _____.", a: "Stakeholders" },
  { id: 187, category: "Requirements Engineering", q: "Why must a company's initial requirements for a large contract be written abstractly?", a: "To allow several contractors to bid without pre-defining the solution." },
  { id: 188, category: "Requirements Engineering", q: "What do functional requirements specifically describe?", a: "Functionality or system services." },
  { id: 189, category: "Requirements Engineering", q: "How do functional user requirements differ from functional system requirements in terms of detail?", a: "User requirements are high-level statements, while system requirements describe services in detail." },
  { id: 190, category: "Requirements Engineering", q: "Why is the term 'search' in the Mentcare requirement considered imprecise?", a: "Users may intend to search across all clinics, while developers may implement searching within a single clinic." },
  { id: 191, category: "Requirements Engineering", q: "What does it mean for a set of requirements to be 'complete'?", a: "They include descriptions of all facilities required by the user." },
  { id: 192, category: "Requirements Engineering", q: "What does it mean for a set of requirements to be 'consistent'?", a: "There are no conflicts or contradictions in the requirement descriptions." },
  { id: 193, category: "Requirements Engineering", q: "According to requirements writing guidelines, when should the word 'should' be used?", a: "To indicate a desirable, but not mandatory, requirement." },
  { id: 194, category: "Requirements Engineering", q: "Why should a rationale be included for each requirement?", a: "To explain why the requirement is necessary for the system." },
  { id: 195, category: "Requirements Engineering", q: "What is the problem of 'requirements amalgamation' in natural language specifications?", a: "Several different requirements are expressed together in a single statement." },
  { id: 196, category: "Requirements Engineering", q: "Which notation uses numbered sentences in standard prose to express one requirement per sentence?", a: "Natural language." },
  { id: 197, category: "Requirements Engineering", q: "Why are mathematical specifications often avoided despite being unambiguous?", a: "Most customers do not understand them." },
  { id: 198, category: "Requirements Engineering", q: "In a form-based specification, what do 'pre and post conditions' describe?", a: "The state of the system before and after a function is executed." },
  { id: 199, category: "Requirements Engineering", q: "When are tabular specifications particularly useful in requirements engineering?", a: "When defining a number of possible alternative courses of action." },
  { id: 200, category: "Requirements Engineering", q: "What should the 'Glossary' section of a requirements document contain?", a: "Definitions of all technical terms used in the document." },
  { id: 201, category: "Requirements Engineering", q: "What is the purpose of the 'System evolution' section in a requirements document?", a: "To describe anticipated changes and assumptions to help designers avoid constraining future modifications." },
  { id: 202, category: "Requirements Engineering", q: "Why is a high-level architectural view useful for communicating with stakeholders?", a: "It provides an abstract view of the system that is not cluttered with detail." },
  { id: 203, category: "Requirements Engineering", q: "Which pattern allows for extending the functionality of an existing class at run-time?", a: "The Decorator pattern." },
  { id: 204, category: "Requirements Engineering", q: "In requirements engineering, what is 'Natural language' notation primarily used for?", a: "To write requirements in numbered sentences that are understandable to customers." },
  { id: 205, category: "Requirements Engineering", q: "How does the 'System architecture' chapter in a requirements document assist module developers?", a: "It shows the distribution of functions across system modules at a high level." },
  { id: 206, category: "Requirements Engineering", q: "What defines 'Structured natural language' as a requirements notation?", a: "Requirements are written on a standard form or template to provide specific fields of information." },
  { id: 207, category: "Requirements Engineering", q: "Why is 'Design description language' now rarely used for requirement specification?", a: "It is often too close to programming code, making it difficult for non-technical stakeholders to validate." },
  { id: 208, category: "Requirements Engineering", q: "What is the primary difference between a 'Functional requirement' and a 'Non-functional requirement' confusion in natural language?", a: "Functional requirements define what a system does, while non-functional requirements define how it performs, and they are often mixed up." },
  { id: 209, category: "Requirements Engineering", q: "Define 'Requirements imprecision' in software engineering.", a: "The problem that arises when functional requirements are not stated with enough detail to avoid multiple interpretations." },
  { id: 210, category: "Requirements Engineering", q: "In the Mentcare functional requirements, what must be generated daily for each clinic?", a: "A list of patients who are expected to attend appointments that day." },
  { id: 211, category: "Requirements Engineering", q: "According to the requirements document structure, where should 'product and process standards' be specified?", a: "In the User requirements definition section." },
  { id: 212, category: "Requirements Engineering", q: "What is the role of 'Appendices' in a standard requirements document?", a: "To provide detailed, specific information like hardware or database descriptions." }
  // ── Safety & Risk Engineering ──

,
  { id: 213, category: "Safety & Risk Engineering", q: "The acceptability of a risk is determined by human, social, and _____ considerations.", a: "political" },
  { id: 214, category: "Safety & Risk Engineering", q: "Why is risk assessment considered subjective?", a: "Because the identification of risks as 'probable' or 'unlikely' depends on the person making the assessment." },
  { id: 215, category: "Safety & Risk Engineering", q: "What are the two factors estimated during hazard assessment?", a: "Risk probability and risk severity." },
  { id: 216, category: "Safety & Risk Engineering", q: "What is the primary goal of hazard assessment in safety engineering?", a: "To exclude risks that are likely to arise." },
  { id: 217, category: "Safety & Risk Engineering", q: "Social acceptability: Boundaries between regions are pushed _____ with time as society is less willing to accept risk.", a: "upwards" },
  { id: 218, category: "Safety & Risk Engineering", q: "Define 'Risk Probability'.", a: "The estimated likelihood that a specific risk will occur." },
  { id: 219, category: "Safety & Risk Engineering", q: "Define 'Risk Severity'.", a: "The estimated impact or damage caused if a risk occurs." },
  { id: 220, category: "Safety & Risk Engineering", q: "The aim of hazard assessment must be to exclude risks that are _____.", a: "likely to arise" },
  { id: 221, category: "Safety & Risk Engineering", q: "Risk assessment depends on _____ is making the assessment.", a: "who" },
  { id: 222, category: "Safety & Risk Engineering", q: "A risk assessment that uses values like 'unlikely' or 'rare' is called a _____ assessment.", a: "relative (or qualitative)" },
  { id: 223, category: "Safety & Risk Engineering", q: "What software attribute covers reliability, security, and safety to prevent physical or economic damage?", a: "Dependability" },
  { id: 224, category: "Safety & Risk Engineering", q: "What do safety-critical control systems require before development to ensure correctness?", a: "A complete and analyzable specification" },
  { id: 225, category: "Safety & Risk Engineering", q: "Why is it safer to name constants that represent real-world values (like tax rates) instead of using literals?", a: "It reduces the likelihood of typing the wrong value and makes updates easier when the value changes." },
  { id: 226, category: "Safety & Risk Engineering", q: "Risk acceptability is not solely technical; it is determined by _____, social, and political considerations.", a: "Human" },
  { id: 227, category: "Safety & Risk Engineering", q: "In hazard assessment, what two factors are estimated for each risk?", a: "Risk probability and risk severity" },
  { id: 228, category: "Safety & Risk Engineering", q: "Why is software behavior directly related to the overall safety of a software-controlled system?", a: "Decisions made by the software and their subsequent actions are often safety-critical." },
  { id: 229, category: "Safety & Risk Engineering", q: "How does monitoring software in an aircraft engine function as a safety-critical component?", a: "It looks for early indications of component failure to prevent accidents caused by other parts." },
  { id: 230, category: "Safety & Risk Engineering", q: "In the context of system safety, distinguish reliability from safety regarding specifications.", a: "Reliability is conformance to a specification, while safety is ensuring no damage regardless of specification conformance." },
  { id: 231, category: "Safety & Risk Engineering", q: "Why are reliability and availability considered necessary but not sufficient conditions for system safety?", a: "A system can be perfectly reliable by following an incorrect specification that leads to an accident." },
  { id: 232, category: "Safety & Risk Engineering", q: "How can a system be considered 'unsafe' despite being 'reliable'?", a: "It may behave exactly as specified while still causing an accident due to specification errors." },
  { id: 233, category: "Safety & Risk Engineering", q: "What is the primary danger of dormant faults in a safety-critical system?", a: "They can remain undetected for years and only manifest under rare, specific conditions." },
  { id: 234, category: "Safety & Risk Engineering", q: "Describe how hardware failures can lead to unsafe behavior in a reliable software system.", a: "Hardware failures can generate spurious inputs that the software specification did not anticipate." },
  { id: 235, category: "Safety & Risk Engineering", q: "What characterizes 'context-sensitive commands' as a source of system risk?", a: "Issuing the correct command at the wrong time, often as a result of operator error." },
  { id: 236, category: "Safety & Risk Engineering", q: "Define 'Hazard Severity' in the context of safety-critical systems.", a: "An assessment of the worst possible damage, ranging from minor to catastrophic, resulting from a hazard." },
  { id: 237, category: "Safety & Risk Engineering", q: "What is the assessment of hazard severity if an individual death is a possibility?", a: "'Very high'." },
  { id: 238, category: "Safety & Risk Engineering", q: "How is 'Hazard Probability' typically categorized in risk assessment?", a: "On an arbitrary scale ranging from 'probable' (e.g., $1/100$) to 'implausible'." },
  { id: 239, category: "Safety & Risk Engineering", q: "State the three factors used to calculate total 'Risk' in a safety-critical system.", a: "Hazard probability, hazard severity, and the probability that the hazard leads to an accident." },
  { id: 240, category: "Safety & Risk Engineering", q: "What is the 'Intolerable' risk category in hazard assessment?", a: "A risk level that must never arise or result in an accident under any circumstances." },
  { id: 241, category: "Safety & Risk Engineering", q: "Define the ALARP region in risk management.", a: "The 'As Low As Reasonably Practical' region where risks are minimized within cost and schedule constraints." },
  { id: 242, category: "Safety & Risk Engineering", q: "Under what condition is a risk categorized as 'Acceptable'?", a: "When the consequences are low enough that no extra costs should be incurred to reduce probability." },
  { id: 243, category: "Safety & Risk Engineering", q: "How does the 'Risk Triangle' represent the relationship between risk levels and tolerability?", a: "It shows an unacceptable region at the top, an ALARP region in the middle, and an acceptable region at the base." },
  { id: 244, category: "Safety & Risk Engineering", q: "Why is the boundary of acceptable risk often pushed upwards in the risk triangle over time?", a: "Social and political considerations change, making societies less willing to accept certain risks." },
  { id: 245, category: "Safety & Risk Engineering", q: "Explain why risk assessment is fundamentally subjective.", a: "The identification of risks as 'probable' or 'unlikely' depends entirely on the individual or group making the assessment." },
  { id: 246, category: "Safety & Risk Engineering", q: "Distinguish between inductive and deductive techniques in hazard analysis.", a: "Inductive is bottom-up (failure to hazard); deductive is top-down (hazard to root causes)." },
  { id: 247, category: "Safety & Risk Engineering", q: "Explain why 'Floating-point numbers' are considered error-prone in safety-critical code.", a: "They are inherently imprecise, which can lead to invalid or unexpected comparisons." },
  { id: 248, category: "Safety & Risk Engineering", q: "What are the risks associated with using 'Pointers' in safety-critical software?", a: "They can refer to the wrong memory areas, corrupt data, and aliasing makes code hard to understand." },
  { id: 249, category: "Safety & Risk Engineering", q: "What is the primary reliability risk of using 'Recursion'?", a: "Logic errors can cause memory overflow as the program stack fills up indefinitely." },
  { id: 250, category: "Safety & Risk Engineering", q: "In hazard classification for an insulin pump, why is 'Insulin overdose' considered 'Intolerable'?", a: "The accident severity is high (potential death) and the estimated risk is high." },
  { id: 251, category: "Safety & Risk Engineering", q: "Why is 'Power failure' in an insulin pump classified as 'Acceptable' risk?", a: "While the probability is high, the accident severity (underdose) is considered low." },
  { id: 252, category: "Safety & Risk Engineering", q: "What is 'Hazard Analysis' primarily concerned with?", a: "Discovering the root causes of risks within a specific system." },
  { id: 253, category: "Safety & Risk Engineering", q: "How does an 'Inductive' hazard analysis approach begin?", a: "With a proposed system failure, then assessing the hazards that could arise from it." },
  { id: 254, category: "Safety & Risk Engineering", q: "How does a 'Deductive' hazard analysis approach begin?", a: "With a specific hazard, then deducing the possible system states that could cause it." },
  { id: 255, category: "Safety & Risk Engineering", q: "What is the risk of using 'Pointer arithmetic' in safety-critical systems?", a: "It increases the likelihood of pointers referring to incorrect memory locations, causing corruption." },
  { id: 256, category: "Safety & Risk Engineering", q: "Safety and reliability are related but _____.", a: "Distinct" },
  { id: 257, category: "Safety & Risk Engineering", q: "If a system behaves as specified but causes an accident, the root cause is a _____ error.", a: "Specification" },
  { id: 258, category: "Safety & Risk Engineering", q: "The 'Top-down' approach to hazard analysis is called _____ analysis.", a: "Deductive" },
  { id: 259, category: "Safety & Risk Engineering", q: "The 'Bottom-up' approach to hazard analysis is called _____ analysis.", a: "Inductive" },
  { id: 260, category: "Safety & Risk Engineering", q: "Software used to monitor aircraft engine components is safety-critical because its failure allows _____ to cause accidents.", a: "Other component failures" },
  { id: 261, category: "Safety & Risk Engineering", q: "The region of the risk triangle where risk cannot be tolerated is the _____ region.", a: "Unacceptable" },
  { id: 262, category: "Safety & Risk Engineering", q: "What three types of considerations determine the social acceptability of a risk?", a: "Human, social, and political considerations." },
  { id: 263, category: "Safety & Risk Engineering", q: "Why do boundaries between acceptable and unacceptable risk regions typically push upwards over time?", a: "Society becomes less willing to accept risk as time progresses." },
  { id: 264, category: "Safety & Risk Engineering", q: "On what does the subjective categorization of a risk as 'probable' or 'unlikely' depend?", a: "It depends on the individual or entity making the assessment." },
  { id: 265, category: "Safety & Risk Engineering", q: "Why are relative values like 'rare' or 'very high' used in hazard assessment instead of precise figures?", a: "It is not normally possible to estimate risk probability and severity precisely." },
  { id: 266, category: "Safety & Risk Engineering", q: "What is the primary aim when performing hazard assessment for a system?", a: "The aim is to exclude risks that are likely to arise." },
  { id: 267, category: "Safety & Risk Engineering", q: "Under what condition does a system's behavior lie outside the scope of a formal safety proof?", a: "When the system is used in a way that was not anticipated by the proof's assumptions." },
  { id: 268, category: "Safety & Risk Engineering", q: "Under what sugar level condition is the insulin pump's 'CompDose' set to zero?", a: "If the sugar level is stable, falling, or increasing at a decreasing rate." },
  { id: 269, category: "Safety & Risk Engineering", q: "In requirements documentation, what is the risk of using 'computer jargon'?", a: "It may alienate or confuse stakeholders who do not have a technical background." }
  // ── Software Engineering Fundamentals ──

,
  { id: 270, category: "Software Engineering Fundamentals", q: "What are the four fundamental software engineering activities?", a: "Software specification, software development, software validation, and software evolution." },
  { id: 271, category: "Software Engineering Fundamentals", q: "What are the four essential attributes of good software?", a: "Maintainability, dependability and security, efficiency, and acceptability." },
  { id: 272, category: "Software Engineering Fundamentals", q: "Define the software attribute 'Maintainability'.", a: "Software written so it can evolve to meet the changing needs of customers." },
  { id: 273, category: "Software Engineering Fundamentals", q: "What does 'Efficiency' in software include besides processing time?", a: "Responsiveness and memory utilization." },
  { id: 274, category: "Software Engineering Fundamentals", q: "Define 'Acceptability' in the context of software quality.", a: "The software must be understandable, usable, and compatible with other systems the users use." },
  { id: 275, category: "Software Engineering Fundamentals", q: "What is the primary focus of 'Software Validation'?", a: "Checking that the software does what the customer wants." },
  { id: 276, category: "Software Engineering Fundamentals", q: "What are 'Software Process Models'?", a: "Abstract representations of the activities involved in producing a software system." },
  { id: 277, category: "Software Engineering Fundamentals", q: "List three examples of general software process models.", a: "Waterfall model, incremental development, and reuse-oriented development." },
  { id: 278, category: "Software Engineering Fundamentals", q: "In the early stages of software engineering, objects usually represent _____.", a: "real-world entities (e.g., patient, doctor, prescription)" },
  { id: 279, category: "Software Engineering Fundamentals", q: "Define 'Software Design'.", a: "A creative activity in which software components and their relationships are identified based on requirements." },
  { id: 280, category: "Software Engineering Fundamentals", q: "What is 'Configuration Management'?", a: "The process of managing changes to an evolving software system." },
  { id: 281, category: "Software Engineering Fundamentals", q: "In host-target development, what is the 'Host'?", a: "The machine used to develop the software, typically running an IDE." },
  { id: 282, category: "Software Engineering Fundamentals", q: "In host-target development, what is the 'Target'?", a: "The machine on which the software is transferred and executed." },
  { id: 283, category: "Software Engineering Fundamentals", q: "What is 'Open Source Development'?", a: "A process where the source code of a system is made publicly available for propose changes and improvements." },
  { id: 284, category: "Software Engineering Fundamentals", q: "What is the benefit of naming constants that represent real-world values (like tax rates)?", a: "It reduces errors and makes the code easier to update when those values change." },
  { id: 285, category: "Software Engineering Fundamentals", q: "List three areas AI is reshaping in modern society.", a: "Healthcare, education, and industry." },
  { id: 286, category: "Software Engineering Fundamentals", q: "Software design and implementation activities are invariably _____.", a: "inter-leaved" },
  { id: 287, category: "Software Engineering Fundamentals", q: "Define 'Software Validation'.", a: "The process of checking that the system does what the customer expects." },
  { id: 288, category: "Software Engineering Fundamentals", q: "What is an 'Abstract Representation' of a software process called?", a: "A software process model." },
  { id: 289, category: "Software Engineering Fundamentals", q: "Software engineering is a/an _____ discipline.", a: "engineering" },
  { id: 290, category: "Software Engineering Fundamentals", q: "The economics of all developed nations are dependent on _____.", a: "software" },
  { id: 291, category: "Software Engineering Fundamentals", q: "Software design involves identifying software _____ and their relationships.", a: "components" },
  { id: 292, category: "Software Engineering Fundamentals", q: "Configuration management is essential when a _____ of people are developing software.", a: "team" },
  { id: 293, category: "Software Engineering Fundamentals", q: "In host-target development, an _____ is typically used on the host machine.", a: "IDE (Integrated Development Environment)" },
  { id: 294, category: "Software Engineering Fundamentals", q: "What is the primary benefit of reusing existing software components?", a: "Reduced development time and cost by utilizing proven software." },
  { id: 295, category: "Software Engineering Fundamentals", q: "A system that is available 90% of the time will be unavailable for _____ minutes in 24 hours.", a: "144" },
  { id: 296, category: "Software Engineering Fundamentals", q: "The goal of software engineering is to produce _____ software in a cost-effective way.", a: "professional" },
  { id: 297, category: "Software Engineering Fundamentals", q: "Software has to _____ quickly to reflect changing business needs.", a: "evolve" },
  { id: 298, category: "Software Engineering Fundamentals", q: "One of the greatest benefits of AI is its ability to process _____.", a: "large amounts of data quickly and accurately" },
  { id: 299, category: "Software Engineering Fundamentals", q: "Which software attribute ensures malicious users cannot access or damage the system?", a: "Security" },
  { id: 300, category: "Software Engineering Fundamentals", q: "Software processes are the activities involved in _____ a software system.", a: "producing" },
  { id: 301, category: "Software Engineering Fundamentals", q: "In host-target development, software is _____ to a target machine for execution.", a: "transferred" },
  { id: 302, category: "Software Engineering Fundamentals", q: "Software is deeply integrated into _____ life.", a: "everyday" },
  { id: 303, category: "Software Engineering Fundamentals", q: "What type of software systems control more and more modern devices?", a: "Software-controlled systems" },
  { id: 304, category: "Software Engineering Fundamentals", q: "What is the fraction of time a system is available for use called?", a: "Availability" },
  { id: 305, category: "Software Engineering Fundamentals", q: "Term: Software Engineering", a: "Definition: An engineering discipline concerned with all aspects of software production." },
  { id: 306, category: "Software Engineering Fundamentals", q: "Which attribute of good software ensures it can evolve to meet the changing needs of customers?", a: "Maintainability" },
  { id: 307, category: "Software Engineering Fundamentals", q: "The software attribute ensuring that system resources are not used wastefully is called _____.", a: "Efficiency" },
  { id: 308, category: "Software Engineering Fundamentals", q: "Which software attribute focuses on the appropriate user interface and documentation for the intended users?", a: "Usability" },
  { id: 309, category: "Software Engineering Fundamentals", q: "Name the fundamental software engineering activity that involves establishing what services are required and their constraints.", a: "Software specification" },
  { id: 310, category: "Software Engineering Fundamentals", q: "Which fundamental software engineering activity involves producing the software system?", a: "Software development" },
  { id: 311, category: "Software Engineering Fundamentals", q: "What software engineering activity ensures that the software does what the customer requires?", a: "Software validation" },
  { id: 312, category: "Software Engineering Fundamentals", q: "In general software engineering, roughly what percentage of costs are attributed to testing?", a: "$40\\%$" },
  { id: 313, category: "Software Engineering Fundamentals", q: "For custom software, which costs often exceed the initial development costs?", a: "Evolution costs" },
  { id: 314, category: "Software Engineering Fundamentals", q: "What specific technique is considered appropriate for developing game software?", a: "A series of prototypes" },
  { id: 315, category: "Software Engineering Fundamentals", q: "How has the web influenced software engineering regarding system architecture?", a: "It enabled highly distributed service-based systems." },
  { id: 316, category: "Software Engineering Fundamentals", q: "Term: Generic software products", a: "Definition: Stand-alone systems marketed and sold to any customer, such as graphics programs or CAD software." },
  { id: 317, category: "Software Engineering Fundamentals", q: "Term: Customized software products", a: "Definition: Software commissioned by a specific customer to meet their own needs, such as air traffic control systems." },
  { id: 318, category: "Software Engineering Fundamentals", q: "According to the ACM/IEEE Code of Ethics, software engineers shall act consistently with the _____ interest.", a: "Public" },
  { id: 319, category: "Software Engineering Fundamentals", q: "To whom must a software engineer's actions be consistent with when acting in the interest of a client or employer?", a: "The public interest" },
  { id: 320, category: "Software Engineering Fundamentals", q: "Which ethical principle requires engineers to ensure products meet the highest professional standards possible?", a: "Product" },
  { id: 321, category: "Software Engineering Fundamentals", q: "What quality must software engineers maintain in their professional judgment according to the Code of Ethics?", a: "Integrity and independence" },
  { id: 322, category: "Software Engineering Fundamentals", q: "Managers and leaders must subscribe to an ethical approach to the _____ of software development.", a: "Management" },
  { id: 323, category: "Software Engineering Fundamentals", q: "Which ethical principle involves advancing the integrity and reputation of the profession?", a: "Profession" },
  { id: 324, category: "Software Engineering Fundamentals", q: "Software engineers must be _____ to and supportive of their colleagues.", a: "Fair" },
  { id: 325, category: "Software Engineering Fundamentals", q: "The ethical principle 'SELF' requires software engineers to participate in _____.", a: "Lifelong learning regarding the practice of their profession" },
  { id: 326, category: "Software Engineering Fundamentals", q: "Term: Integration and configuration", a: "Definition: A process where the system is assembled from existing configurable components." },
  { id: 327, category: "Software Engineering Fundamentals", q: "In the waterfall model, what phase follows 'System and software design'?", a: "Implementation and unit testing" },
  { id: 328, category: "Software Engineering Fundamentals", q: "What is the final phase of the waterfall model?", a: "Operation and maintenance" },
  { id: 329, category: "Software Engineering Fundamentals", q: "What is the main drawback of using the waterfall model?", a: "The difficulty of accommodating change after the process is underway." },
  { id: 330, category: "Software Engineering Fundamentals", q: "The waterfall model is mostly used for large systems engineering projects where development happens at _____.", a: "Several sites" },
  { id: 331, category: "Software Engineering Fundamentals", q: "Which development model allows for more rapid delivery and deployment of useful software to the customer?", a: "Incremental development" },
  { id: 332, category: "Software Engineering Fundamentals", q: "Process: Software design", a: "Action: Identify software components and their relationships based on customer requirements." },
  { id: 333, category: "Software Engineering Fundamentals", q: "Process: Implementation", a: "Action: Realize the software design as an executable program." },
  { id: 334, category: "Software Engineering Fundamentals", q: "What process metric captures the calendar time or effort required to complete an activity?", a: "Time" },
  { id: 335, category: "Software Engineering Fundamentals", q: "Give an example of a process metric categorized under 'Resources'.", a: "Total effort in person-days" },
  { id: 336, category: "Software Engineering Fundamentals", q: "Which process metric is used to track the number of defects discovered?", a: "Number of occurrences of a particular event" },
  { id: 337, category: "Software Engineering Fundamentals", q: "At which SEI Capability Maturity Level is the process described as 'essentially uncontrolled'?", a: "Level 1: Initial" },
  { id: 338, category: "Software Engineering Fundamentals", q: "In which SEI Capability Maturity Level are product management procedures first defined and used?", a: "Level 2: Repeatable" },
  { id: 339, category: "Software Engineering Fundamentals", q: "Term: Managed (CMM Level 4)", a: "Definition: The maturity level where quality management strategies are defined and used." },
  { id: 340, category: "Software Engineering Fundamentals", q: "What is the goal of the 'Optimising' level (Level 5) in the CMM framework?", a: "The use of defined process improvement strategies." },
  { id: 341, category: "Software Engineering Fundamentals", q: "Maturity-based approaches to process improvement focus on better process management and _____.", a: "The use of good software engineering practice" },
  { id: 342, category: "Software Engineering Fundamentals", q: "What does COTS stand for in software procurement?", a: "Commercial Off-The-Shelf systems" },
  { id: 343, category: "Software Engineering Fundamentals", q: "Term: Configuration management", a: "Definition: The process of managing changes to an evolving software system." },
  { id: 344, category: "Software Engineering Fundamentals", q: "In host-target development, where is the software executed?", a: "The target machine" },
  { id: 345, category: "Software Engineering Fundamentals", q: "What is the primary characteristic of open source development?", a: "The source code is made publicly available for people to propose changes and improvements." },
  { id: 346, category: "Software Engineering Fundamentals", q: "What is the primary challenge in judging the 'completeness' of a test set?", a: "A large number of system tests does not guarantee complete code or scenario coverage." },
  { id: 347, category: "Software Engineering Fundamentals", q: "What is the goal of the 'Prioritization and Negotiation' stage in RE?", a: "To resolve conflicts between requirements and decide which are most critical." },
  { id: 348, category: "Software Engineering Fundamentals", q: "What are the core components of a Language Processing System architecture?", a: "A translator and an abstract machine that executes the generated language." },
  { id: 349, category: "Software Engineering Fundamentals", q: "Define 'Transaction Processing Systems' in an architectural context.", a: "Interactive systems allowing multiple users to remotely access and modify information in a database." },
  { id: 350, category: "Software Engineering Fundamentals", q: "What is 'Host-target development'?", a: "Developing software on one machine (host) using an IDE and executing it on another (target)." },
  { id: 351, category: "Software Engineering Fundamentals", q: "What is the defining characteristic of 'Open source development'?", a: "Making the system source code public so anyone can propose changes or improvements." },
  { id: 352, category: "Software Engineering Fundamentals", q: "What is 'Aliasing' and why is it dangerous?", a: "Using more than one name for the same state variable, which obscures state changes and causes errors." },
  { id: 353, category: "Software Engineering Fundamentals", q: "Why is it recommended to name constants representing real-world values (like tax rates)?", a: "It prevents mistakes from typing wrong numeric values and makes the code easier to update when values change." },
  { id: 354, category: "Software Engineering Fundamentals", q: "An erroneous internal state that may lead to unexpected behavior is a _____.", a: "System Error" },
  { id: 355, category: "Software Engineering Fundamentals", q: "The 'As Low As Reasonably Practical' principle is abbreviated as _____.", a: "ALARP" },
  { id: 356, category: "Software Engineering Fundamentals", q: "A 24-hour period contains _____ minutes.", a: "$1,440$" },
  { id: 357, category: "Software Engineering Fundamentals", q: "Using multiple names to refer to the same state variable is called _____.", a: "Aliasing" },
  { id: 358, category: "Software Engineering Fundamentals", q: "Buffer overflow is a common result of using _____ arrays.", a: "Unbounded" },
  { id: 359, category: "Software Engineering Fundamentals", q: "In RE, _____ involves technical staff working with customers to find the application domain.", a: "Elicitation" },
  { id: 360, category: "Software Engineering Fundamentals", q: "In an iLearn digital learning environment, what determines the specific set of tools included in a particular version?", a: "Teachers and learners choose tools to suit their specific needs." },
  { id: 361, category: "Software Engineering Fundamentals", q: "The framework of an iLearn environment allows for the embedding of general-purpose tools and what other category of applications?", a: "Applications geared to the needs of the learners using the system." },
  { id: 362, category: "Software Engineering Fundamentals", q: "Provide an example of a learning management application that might be embedded in a digital learning environment.", a: "A Virtual Learning Environment (VLE) for homework submission and assessment." },
  { id: 363, category: "Software Engineering Fundamentals", q: "A company might find that cleaning up pollution is cheaper than prevention; why might this approach be rejected?", a: "It may not be socially acceptable." },
  { id: 364, category: "Software Engineering Fundamentals", q: "How does a model checker verify that a user-specified property is valid for a system?", a: "It explores all possible paths through the system model." },
  { id: 365, category: "Software Engineering Fundamentals", q: "On what two factors does a customer base the selection of stories for the next software release?", a: "Priority and schedule estimates." },
  { id: 366, category: "Software Engineering Fundamentals", q: "In the medication prescribing story, what is the 'dose checking' task's specific purpose?", a: "To ensure the doctor hasn't prescribed a dangerously small or large dose." },
  { id: 367, category: "Software Engineering Fundamentals", q: "What logic governs the enabling of the 'Confirm' button in the medication dose checking task?", a: "The button is enabled only if the prescribed dose is within the recommended minimum and maximum range." },
  { id: 368, category: "Software Engineering Fundamentals", q: "What specific component of a complex user interface is noted as being difficult to unit test incrementally?", a: "The code implementing 'display logic' and workflow between screens." },
  { id: 369, category: "Software Engineering Fundamentals", q: "What is the main difficulty in assessing the quality of a set of system tests?", a: "It is difficult to judge the completeness or coverage of the test set." },
  { id: 370, category: "Software Engineering Fundamentals", q: "What is the purpose of the detailed system definition written after a contract is awarded?", a: "To allow the client to understand and validate the proposed system." },
  { id: 371, category: "Software Engineering Fundamentals", q: "In the Mentcare system, what is the mandatory length for a staff member's employee number?", a: "It must be exactly $8$ digits." },
  { id: 372, category: "Software Engineering Fundamentals", q: "What is the pre-condition for computing an insulin dose?", a: "The reservoir must contain at least the maximum allowed single dose of insulin." },
  { id: 373, category: "Software Engineering Fundamentals", q: "What is 'configuration management' in software development?", a: "The process of managing changes to an evolving software system." },
  { id: 374, category: "Software Engineering Fundamentals", q: "Distinguish between a 'host' and a 'target' machine in software development.", a: "Software is developed on a host machine using an IDE and transferred to a target machine for execution." },
  { id: 375, category: "Software Engineering Fundamentals", q: "What is the main implication of 'Open source development' for software improvement?", a: "The source code is public, allowing many people to propose changes and improvements." },
  { id: 376, category: "Software Engineering Fundamentals", q: "Why must software and hardware be 'diverse' in a multi-channel self-monitoring system?", a: "To prevent a common mode failure or error from affecting every channel simultaneously." },
  { id: 377, category: "Software Engineering Fundamentals", q: "What is the pedagogical benefit of naming constants that represent real-world values?", a: "It reduces mistakes because programmers are less likely to type the wrong value when using a name." },
  { id: 378, category: "Software Engineering Fundamentals", q: "List three examples of variables that should be treated as named constants due to their real-world nature.", a: "Tax rates, physical constants, or conversion factors." },
  { id: 379, category: "Software Engineering Fundamentals", q: "What does a model checker do when it encounters a 'user-specified property' that is invalid on a specific path?", a: "It identifies the error in the model." }
  // ── System Modeling & UML ──

,
  { id: 380, category: "System Modeling & UML", q: "In a UML Class Diagram, what does an 'Association' represent?", a: "A link between classes indicating a relationship between them." },
  { id: 381, category: "System Modeling & UML", q: "What is an 'Object Class' in system modeling?", a: "A general definition of one kind of system object." },
  { id: 382, category: "System Modeling & UML", q: "In system modeling, an association is a _____ between classes.", a: "link" },
  { id: 383, category: "System Modeling & UML", q: "In UML class diagrams, the number '1' next to an association line usually represents _____.", a: "multiplicity (one-to-one relationship)" },
  { id: 384, category: "System Modeling & UML", q: "What is 'System Modeling'?", a: "The process of developing abstract models of a system." },
  { id: 385, category: "System Modeling & UML", q: "In UML modeling, what does a class diagram's association multiplicity of '$1..*$' indicate?", a: "One or more instances are involved in the relationship." },
  { id: 386, category: "System Modeling & UML", q: "What technique is used in system modeling to manage complexity by grouping entities into broader classes?", a: "Generalization." },
  { id: 387, category: "System Modeling & UML", q: "In generalization, what are members of a subclass able to do regarding the characteristics of the superclass?", a: "They inherit or share the common characteristics of the more general class." }
  // ── Verification & Static Analysis ──

,
  { id: 388, category: "Verification & Static Analysis", q: "Static analysis: What is a 'Memory leak' classified as?", a: "A storage management fault." },
  { id: 389, category: "Verification & Static Analysis", q: "Term: Assertion checking (Static Analysis)", a: "Definition: Developers include formal relationships that must hold, and the analyzer highlights potential problems by symbolically executing the code." },
  { id: 390, category: "Verification & Static Analysis", q: "Why is static analysis particularly valuable for the C programming language?", a: "C has weak typing, which allows many errors to go undetected by the compiler." },
  { id: 391, category: "Verification & Static Analysis", q: "Static analysis can discover areas of vulnerability such as buffer overflows or _____ inputs.", a: "Unchecked" },
  { id: 392, category: "Verification & Static Analysis", q: "Which static analysis category identifies variables output twice with no intervening assignment?", a: "Input/output faults." },
  { id: 393, category: "Verification & Static Analysis", q: "What is the first step in the process of model checking a system?", a: "Creating an extended finite state model of the system." },
  { id: 394, category: "Verification & Static Analysis", q: "For which specific type of systems is model checking considered particularly valuable due to testing difficulties?", a: "Concurrent systems." },
  { id: 395, category: "Verification & Static Analysis", q: "What is the primary disadvantage of model checking as a verification technique?", a: "It is computationally very expensive." },
  { id: 396, category: "Verification & Static Analysis", q: "What does it mean for a verification process to be 'Robust'?", a: "The process should be able to recover from the failure of individual activities." },
  { id: 397, category: "Verification & Static Analysis", q: "Why is static analysis particularly useful for identifying 'uncalled functions'?", a: "These functions represent dead code that increases complexity without adding value." }

];